### PR TITLE
Upload Silero Text-to-Speech Models

### PR DESCRIPTION
**Pull request by snakers4**
Hi,

Please kindly review our TTS models

### CODE REVIEW

**Comment by snakers4** [comment]
Hi @ailzhang and @soumith 

Check out our brand new PR to torchhub!

- You can see more details about these models here - https://habr.com/ru/post/549482/
- This is kind of similar to Nvidia's Tacotron and Waveglow ... but it works decently on 1 CPU thread now and it is end-to-end in one package
- Some tldr info from our materials below as well;

**Speakers** 

10 voices (each available in 16 kHz and 8 kHz):

- 6 Russian voices;
- 1 English voice;
- 1 German voice, 1 Spanish voice, 1 French voice;

**Why is this Different?**

- One-line usage;
- A large library of voices;
- A fully end-to-end pipeline;
- Naturally sounding speech;
- No GPU or training required;
- Minimalism and lack of dependencies;
- Faster than real-time on one CPU thread (!!!);
- Support for 16kHz and 8kHz out of the box;

**Review by ailzhang — COMMENTED** [review]
Thanks @snakers4 for contributing! 
Stamping to confirm the netlify job failure is just flaky. 
Pinged internally to get some help on reviewing the model code. :D

**Comment by snakers4** [comment]
> Pinged internally to get some help on reviewing the model code

Is there anything you would like to know?

**Comment by mthrok** [comment]
@ailzhang What is the criteria for `reviewing the model code` here?

Are we expecting security vulnerabilities?
I assume that models from Silero are all TorchScript-ed, so there is no `torch.nn.Module`-based code for the model. (@snakers4 correct me if I am wrong)

**Comment by snakers4** [comment]
Yes, all of the models are either torchscripted `jit` files or quantized torchscripted `jit` files

All of the code is either in utils or model packages
This greatly simplifies everything

There are also onnx files and sometimes tf files, but they are not presented here and probably tf files will not be supported in future

**Review by mthrok — APPROVED** [review]
I did not looked into the model code because it's scripted but played around it on the linked Colab Notebook and think this is a nice addition to Torch Hub.

**Comment by snakers4** [comment]
Many thanks

**Comment by snakers4** [comment]
We did our best to share the non-commerial release in Russian (https://habr.com/ru/post/549480/) and in English (https://habr.com/ru/post/549482/), i.e. links shared via hackernews / twitter / personal shares / telegram channels

And so far it seems that the English article goes mostly unnoticed while the Russian one exploded
If you have any practice of giving shout-outs to torchhub additions that would be awesome

**Pull request merged**
