### PR TITLE
Update template.md

### PR DESCRIPTION
**Pull request by Riser6**
request to  publish YOLOP model

### CODE REVIEW

**Review by NicolasHug — COMMENTED** [review]
Thanks for the PR @Riser6 ,

 instead of editing the docs/template.md file, please just create a new file named `<repo_owner>_<repo_name>_<title>.md` at the root of the directory, like the other ones which you can see at https://github.com/pytorch/hub

**Comment by Riser6** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        I see. Thank you for reminding me!
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1528152501
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 9/2/2021 23:12，Nicolas ***@***.***> wrote： 



@NicolasHug commented on this pull request.

Thanks for the PR @Riser6 ,
instead of editing the docs/template.md file, please just create a new file named <repo_owner>_<repo_name>_<title>.md at the root of the directory, like the other ones which you can see at https://github.com/pytorch/hub

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NicolasHug** [comment]
Since you opened #228 I'll close this one

**Comment by Riser6** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        Ok, thanks!
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1528152501
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 9/2/2021 23:24，Nicolas ***@***.***> wrote： 



Since you opened #228 I'll close this one

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
