### PR TITLE
Add MiDaS to hub

### PR DESCRIPTION
**Pull request by ranftlr**
MiDaS is a general purpose model for monocular depth estimation. It can provide relative depth for a wide range of images. Some example results:

image

Original repository: https://github.com/intel-isl/MiDaS

You can read the paper here: https://arxiv.org/pdf/1907.01341.pdf

### CODE REVIEW

**Comment by valgur** [comment]
One suggestion: the `model.pt` checkpoint file currently has a rather generic name, which could easily collide with some other model in the cache directory. The checkpoint files are stored directly in the `~/.cache/torch/hub/checkpoints` directory without providing any sort of separate namespacing logic, such as by including a prefix or a storing them in separate directories.

An easy way to avoid this is to include the SHA256 checksum suffix in the format supported by [`torch.hub.load_state_dict_from_url()`](https://pytorch.org/docs/stable/hub.html#torch.hub.load_state_dict_from_url). You might find this [`torch_add_hash.sh`](https://gist.github.com/valgur/be533962476f0aac8a44e5ad40d66c6d) script useful for this. So, a suggested name would be something like `model-f46da743.pt` or `MiDaS-f46da743.pt`.

**Comment by valgur** [comment]
Also, since MiDaS uses custom transformation implementations which are not easily accessible in external code, I would suggest providing them in the hubconf.py file as well. Including the typical inference transformation would be helpful as well.

So, perhaps something like:
```python
def transforms():
    from torchvision.transforms import Compose
    import cv2
    from models.transforms import Resize, NormalizeImage, PrepareForNet
    from models import transforms

    transforms.default_transform = Compose([
        lambda img: {"image": img / 255.},
        Resize(
            384,
            384,
            resize_target=None,
            keep_aspect_ratio=True,
            ensure_multiple_of=32,
            resize_method="upper_bound",
            image_interpolation_method=cv2.INTER_CUBIC,
        ),
        NormalizeImage(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        PrepareForNet(),
        lambda sample: torch.from_numpy(sample["image"]).unsqueeze(0)
    ])
    return transforms
```
Moving the imports inside the function might be a good idea to avoid requiring additional dependencies, such as OpenCV, by default.

As a result, the image loading part of the inference example in the docs could be reduced to just:
```python
midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")
transform = midas_transforms.default_transform

img = cv2.imread(filename)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

input_image = transform(img).to(device)
```

**Comment by ranftlr** [comment]
@valgur Thank you for the helpful pointers! I've updated the code and example accordingly.

It seems that netlify fails for reasons that are unrelated to this PR.

**Comment by ailzhang** [comment]
Netlify failure is not related - I'll take a look later. 
Thanks @ranftlr @valgur !

**Pull request merged**
