### PR TITLE
Add Background-Matting submodule

### PR DESCRIPTION
**Pull request by asuhan**

### CODE REVIEW

**Comment by asuhan** [comment]
@ailzhang Got the training going, failure looks unrelated. However, this model doesn't fit the [`get_module` and train on examples](https://github.com/pytorch/hub/blob/736ade430a47c119cb5f53adef38351786469c72/benchmark/test.py#L12) since it consists of multiple modules. Is the intent of that pattern to warm-up the model?

We could address the missing `eval` / `get_module` or land this as-is for the training part. Please let me know.

**Comment by wconstab** [comment]
hopefully fixed issue with CI, rerunning. sorry about that!

**Comment by asuhan** [comment]
Still not fixed:

```
Traceback (most recent call last):
  File "benchmark/upload_scribe.py", line 130, in <module>
    benchmark_uploader.post_pytest_benchmarks(json_data)
  File "benchmark/upload_scribe.py", line 119, in post_pytest_benchmarks
    self.upload(messages)
  File "benchmark/upload_scribe.py", line 49, in upload
    raise ValueError("Can't find access token from environment variable")
ValueError: Can't find access token from environment variable
```

**Comment by ailzhang** [comment]
Ah @asuhan try rebasing on top of master?

**Pull request merged**
