### PR TITLE
add PPO2 from andompesta

### PR DESCRIPTION
**Pull request by andompesta**
PPO2 implementation based on the original code (https://github.com/openai/baselines/tree/master/baselines/ppo2).

Note that I have also add the rl tag to the tag list.

On the original repository there is an example running gym('CartPole-v0') environment with the relative env.yml file for import. While the network structure is fixed, it is possible to add an encoder module on top of the proposed model to enable multi-model input format. 

Finally, I have no pre-trained weight available since the CartPole-v0 environment is extremely easy to solve for such model

### CODE REVIEW

**Comment by ailzhang** [comment]
A quick tip to get preview working: remove `<!-- Only change fields below -->` line, apparently jekyll doesn't like that. 
I will update the template now.

**Comment by andompesta** [comment]
Yes sure I realized that that informed @ylecun on Twitter already

cheers,
sandro

**Comment by soumith** [comment]
I wrote down some thoughts on what should be in Hub in the initial iteration, and what should wait for the flood gates to open (i.e. without curation) here: https://github.com/pytorch/hub/issues/31#issuecomment-500696324

I think a PPO algorithm would be better served as a library, rather than a Hub "model" -- because it's an algorithm than a model in the strict sense.

**Comment by andompesta** [comment]
I see your point. It is technically difficult to share the parameters for PPO, since different environment/observation requires completely different encoding. Yet, it is possible to define an encoding model over PPO. 

What might be more challenging is the parallelisation of PPO

**Comment by soumith** [comment]
after thinking about it a bit more, i think it's not the right thing to add to hub. I think I stand by my original thought that 

> I think a PPO algorithm would be better served as a library, rather than a Hub "model" -- because it's an algorithm than a model in the strict sense.

If you have a set of RL algorithms, such as PPO implemented, consider making them a library like https://github.com/Kaixhin/Rainbow and then submitting to be included in https://pytorch.org/ecosystem where tools and libraries are included.

**Pull request closed without merging**
