### PR TITLE
add MEAL V2

### PR DESCRIPTION
**Pull request by szq0214**
MEAL V2: Boosting Vanilla ResNet-50 to 80%+ Top-1 Accuracy on ImageNet without Tricks ([https://arxiv.org/abs/2009.08453](https://arxiv.org/abs/2009.08453)). A simple yet effective knowledge distillation approach that can boost the vanilla ResNet-50 to 80%+ Top-1 accuracy on ImageNet without any tricks.

MEALV2_results

Screen Shot 2020-10-07 at 6 12 05 PM

### CODE REVIEW

**Comment by szq0214** [comment]
Hi,

It seems the failure is because 'torch.hub.load_state_dict_from_url()' is not able to load the new zipfile saved with  torch==1.6.0 (https://github.com/pytorch/pytorch/issues/42239). I tested locally with pytorch-nightly and it has no problem, but got the same error with pytorch 1.6.0.

**Comment by ailzhang** [comment]
@szq0214 Thanks for the contribution! There was a bug that we fixed after 1.6 release so it was in nightly but not in 1.6. The easiest workaround is to load the checkpoint locally and redo `torch.save(..., _use_new_zipfile_serialization=False)` and then use that binary for now. 
Once 1.7 is released we should be good with the new checkpoint you current have. Does that sound like a good workaround for you? Thanks!

**Comment by szq0214** [comment]
Hi @ailzhang, thanks for your reply and it sounds good. I will convert my models and push again.

**Comment by ailzhang** [comment]
gentlely ping @soumith on reviewing ;)

**Comment by szq0214** [comment]
Hi,

I added one dependency in install.sh following README but it shows the conflicting file. 

Also, the error on CircleCI is from "model = torch.hub.load('PingoLH/Pytorch-HarDNet', 'hardnet68', pretrained=True)" with "RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU." It seems the error is not on my side. Is there any suggestion to solve them?

**Comment by szq0214** [comment]
@ailzhang @soumith ci appears to be failing due to an unrelated huggingface_pytorch-transformers.md issue. Can you guys help to review this pull request? Thanks!

Screen Shot 2020-12-14 at 12 59 29 PM

**Comment by soumith** [comment]
looks good to me, thanks!

**Pull request merged**
