### PR TITLE
Update from pytorch_pretrained_bert - HuggingFace

### PR DESCRIPTION
**Pull request by VictorSanh**
- Update doc for BERT and GPT from pytorch_pretrained_bert
- Add GPT-2 (small and medium) with doc and examples
- Add Transformer-XL with doc and examples

### CODE REVIEW

**Comment by soumith** [comment]
@VictorSanh I rebased the PR and fixed some bugs. But it's still actually failing to run

This is with the BERT model, which used to run just fine?

```
  File "temp.py", line 50, in <module>
    lm_logits, multiple_choice_logits = double_head_model(tokens_tensor, mc_token_ids)
  File "/home/circleci/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/circleci/.cache/torch/hub/huggingface_pytorch-pretrained-BERT_master/pytorch_pretrained_bert/modeling_openai.py", line 946, in forward
    mc_logits = self.multiple_choice_head(hidden_states, mc_token_ids)
  File "/home/circleci/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/circleci/.cache/torch/hub/huggingface_pytorch-pretrained-BERT_master/pytorch_pretrained_bert/modeling_openai.py", line 424, in forward
    multiple_choice_h = hidden_states.gather(2, mc_token_ids).squeeze(2)
RuntimeError: invalid argument 4: Index tensor must have same dimensions as input tensor at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:440
Exited with code 1
```

**Comment by soumith** [comment]
see https://circleci.com/gh/pytorch/hub/174?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by VictorSanh** [comment]
There were some missing `[]` missing in the last GPT example (I added an example for the `DoubleHeadModel` of GPT). Stupid mistake.
Thank you @soumith for everything!
I corrected it and all the CI checks passed.

**Comment by soumith** [comment]
sweet, thanks for the updates, looks great! :)

**Pull request merged**
