### PR TITLE
Add wide resnet

### PR DESCRIPTION
**Pull request by szagoruyko**
Needs https://github.com/pytorch/vision/pull/912 to be merged first

### CODE REVIEW

**Comment by szagoruyko** [comment]
@fmassa could you please rerun CI on this one, WRN was merged so it should pass now

**Comment by fmassa** [comment]
I don't think I have the rights for it. Maybe closing / reopening the PR?

**Comment by ailzhang** [comment]
Hi @fmassa  I've restarted the test and added you as collaborator :)

**Comment by szagoruyko** [comment]
thanks @ailzhang !
I checked the preview and it looks like we could add a notebook similar to https://github.com/pytorch/pytorch.github.io/blob/site/assets/hub/pytorch_vision_resnet.ipynb, to enable colab edit

**Comment by szagoruyko** [comment]
@soumith I rebased myself, CI passes

**Comment by soumith** [comment]
thanks Sergey!

**Pull request merged**
