### PR TITLE
Pytorch-pretrained-BERT -> PyTorch-Transformers

### PR DESCRIPTION
**Pull request by LysandreJik**
PyTorch Hub now has the AutoModel/Tokenizer/Config objects available, completing the list of models and easing the future addition of new models.

### CODE REVIEW

**Comment by thomwolf** [comment]
Instead of maintaining several `hubconf` files for each model architecture, we now provide common entry points to all the model with unified classes.

Maybe the failing assert in the CI tests is related to that?

**Comment by soumith** [comment]
thank you! I'll fix the CI now, it's just some asserts about the formats of the markdowns.

**Comment by soumith** [comment]
hey, the code is still non-working.

There were actual syntatical errors, which I fixed, and now there are variables missing.

Please see:

https://gist.github.com/soumith/facf85f80e02ea57c61c1e1318c3befe

Current error is: 

```
Traceback (most recent call last):
  File "temp.py", line 25, in <module>
    tokenized_text[masked_index] = '[MASK]'
NameError: name 'tokenized_text' is not defined
```

Can you help fix this?

**Comment by thomwolf** [comment]
Yes, looking at it right now

**Pull request merged**
