### PR TITLE
Adding 3 nvidia convnets models

### PR DESCRIPTION
**Pull request by nv-kkudrynski**
3 new notebooks for Efficientnet, ResneXt and Resnet adapted to Torchhub. FYI @soumith

### CODE REVIEW

**Comment by vmoens** [comment]
General comments: 
- perhaps add training method in titles, to let users know what is the specificities on these models wrt other pre-trained resnet / other models?
- Few rendering issues and typos
Otherwise LGTM! Thanks a lot for the contribution

**Comment by nv-kkudrynski** [comment]
Hi. Thanks! I added the training information to the summary. Can you point out the typos and rendering issues, or correct them right away if they are straightforward?

**Comment by vmoens** [comment]
> Hi. Thanks! I added the training information to the summary. Can you point out the typos and rendering issues, or correct them right away if they are straightforward?

Sure no problem I can do the fixes for the broken links. Can you comment / adjust the other comments I made too? Like the quotes at the end of each file and similar. Thanks!

**Review by vmoens — COMMENTED** [review]
Sorry here's the review

**Review by vmoens — APPROVED** [review]
Awesome, with that and the summaries we're good to go

**Pull request merged**
