### PR TITLE
upgrade torchvision version

### PR DESCRIPTION
**Pull request by parmeet**
https://github.com/pytorch/hub/issues/212
https://github.com/pytorch/hub/issues/208

Upgrading torchvision md files to latest version 0.10.0

### CODE REVIEW

**Review by NicolasHug — APPROVED** [review]
Thanks @parmeet , LGTM

Just curious, did you use `./scripts/upgrade_torchvision.sh` to update?

Regarding the linked issues: I'm afraid this won't solve #212 or #208 yet. But https://github.com/pytorch/pytorch/pull/61761 should fix them

**Comment by parmeet** [comment]
> Thanks @parmeet , LGTM
> 
> Just curious, did you use `./scripts/upgrade_torchvision.sh` to update?
> 
> Regarding the linked issues: I'm afraid this won't solve #212 or #208 yet. But [pytorch/pytorch#61761](https://github.com/pytorch/pytorch/pull/61761) should fix them

Sounds good! Thanks for mentioning the other related issue. Also yes, I used the script. Just that the script doesn't work out of the box on mac, here is the [story]( https://stackoverflow.com/questions/16745988/sed-command-with-i-option-in-place-editing-works-fine-on-ubuntu-but-not-mac) why :)

**Comment by NicolasHug** [comment]
Regarding the last commit:  b631c29 
It seems to be the same as https://github.com/pytorch/hub/pull/215. In order to keep unrelated changes separate, perhaps we should revert this commit and wait for  https://github.com/pytorch/hub/pull/215 to be merged before merging this one?

**Comment by parmeet** [comment]
> Regarding the last commit: [b631c29](https://github.com/pytorch/hub/commit/b631c29a181819612223728b8b057dd8773de8ba)
> It seems to be the same as #215. In order to keep unrelated changes separate, perhaps we should revert this commit and wait for #215 to be merged before merging this one?

unfortunately, the CircleCI testing exits on the first failure.. this was temporarily done to proceed to next testing. not sure, if we should do all the tests and catch all failures instead?

**Pull request merged**
