### PR TITLE
Add Deep Automodulators FFHQ 512x512 model

### PR DESCRIPTION
**Pull request by heljakka**
Propose to add Deep Automodulators ([NeurIPS 2020](https://neurips.cc/virtual/2020/public/poster_9df81829c4ebc9c427b9afe0438dce5a.html)) 512x512 FFHQ model . With an encoder-decoder structure, it allows for direct scale-specific manipulation, mixing, interpolation and unsupervised attribute manipulation of existing face images (as opposed to generator-only models) while retaining reasonably sharp outputs.

### CODE REVIEW

**Review by ailzhang — COMMENTED** [review]
Thanks for contributing! cc:@soumith to take another look before landing.

**Comment by soumith** [comment]
hi @heljakka .

Since the research and the corresponding model seems to involve mixing faces, before publishing a link to it on the PyTorch Hub, I'd like to understand if you have done any research as to understanding the biases encoded in the model.

Can you share any such information available?

**Comment by heljakka** [comment]
> hi @heljakka .
> 
> Since the research and the corresponding model seems to involve mixing faces, before publishing a link to it on the PyTorch Hub, I'd like to understand if you have done any research as to understanding the biases encoded in the model.
> 
> Can you share any such information available?

Hi @soumith ,
We have not yet done experiments to analyse the biases as such. If this is required, do you have a specific recommendation of a method or criteria that would be sufficient in this context? The model is based on the public FFHQ dataset (using face IDs 1-60,000).

**Comment by heljakka** [comment]
In absence of any clarification of the acceptance criteria in terms of model bias, I will close off this PR.

**Pull request closed without merging**
